#!/usr/bin/env python3
"""
RenzBase Offset Updater
Fetches the latest Roblox offsets from one of 3 working mirrors.
Falls through the list if a mirror is down.

Usage:
    python update_offsets.py                    # prints to stdout
    python update_offsets.py -o Offsets.h       # writes C++ header
    python update_offsets.py --mirror femboy    # use specific mirror

Mirrors (verified working as of 2026-09-02):
    - imtheo.lol          (main, theo)
    - femboythighs.org    (dedicated)
    - uwuhook.club        (domain-only, may not have full JSON)
"""

import json
import sys
import urllib.request
import urllib.error
import argparse
from datetime import datetime

MIRRORS = [
    ("theo (main)",        "https://offsets.imtheo.lol/offsets.json"),
    ("femboy (dedicated)", "https://offsets.femboythighs.org/offsets.json"),
    ("uwuhook (domain)",   "https://offsets.uwuhook.club/offsets.json"),
]

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) RenzBase/1.0"

def fetch(url: str, timeout: int = 10) -> dict | None:
    """Try one mirror. Return parsed JSON or None on failure."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8")
        return json.loads(raw)
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError, TimeoutError) as e:
        print(f"  [FAIL] {url}: {type(e).__name__}: {e}", file=sys.stderr)
        return None

def fetch_first_working() -> tuple[str, dict]:
    """Try each mirror in order. Return (mirror_name, json)."""
    print(f"[*] Fetching offsets from {len(MIRRORS)} mirrors...")
    for name, url in MIRRORS:
        print(f"  [TRY] {name} -> {url}")
        data = fetch(url)
        if data and "Offsets" in data:
            print(f"  [OK]  {name} returned {len(data['Offsets'])} offsets")
            return name, data
    print("[!] All mirrors failed", file=sys.stderr)
    sys.exit(1)

def parse_to_cpp(data: dict) -> str:
    """Convert theo's JSON shape to C++ constexpr struct definitions."""
    version = data.get("Roblox Version", "unknown")
    dumper = data.get("Dumper Version", "?")
    dumped = data.get("Dumped At", "?")
    offsets = data["Offsets"]

    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by update_offsets.py — DO NOT EDIT BY HAND",
        f"// Source: theo mirror dump (version={version}, dumped={dumped}, dumper={dumper})",
        f"// Generated: {datetime.utcnow().isoformat()}Z",
        "// ============================================================================",
        "#pragma once",
        "#include <cstdint>",
        "",
        f'inline constexpr const char* kRobloxVersion = "{version}";',
        "",
    ]

    for struct_name, fields in sorted(offsets.items()):
        # If fields is a dict, it's a struct with sub-fields
        if isinstance(fields, dict):
            lines.append(f"struct {struct_name} {{")
            for fname, fval in sorted(fields.items()):
                lines.append(f"    inline static constexpr uintptr_t {fname} = {fval};")
            lines.append("};")
            lines.append("")

    lines.append("// ============================================================================")
    lines.append("// End of auto-generated offsets")
    lines.append("// ============================================================================")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser(description="Fetch latest Roblox offsets for RenzBase")
    ap.add_argument("-o", "--output", help="Write C++ header to this file (default: stdout)")
    ap.add_argument("--json", action="store_true", help="Write raw JSON instead of C++")
    ap.add_argument("--mirror", help="Use specific mirror (imtheo/femboy/uwuhook)")
    args = ap.parse_args()

    if args.mirror:
        # Filter mirrors by name
        name_map = {"imtheo": MIRRORS[0], "femboy": MIRRORS[1], "uwuhook": MIRRORS[2]}
        if args.mirror.lower() not in name_map:
            print(f"[!] Unknown mirror: {args.mirror}. Use: {list(name_map.keys())}")
            sys.exit(1)
        mirror_name, url = name_map[args.mirror.lower()]
        print(f"[*] Using forced mirror: {mirror_name}")
        data = fetch(url)
        if not data:
            sys.exit(1)
    else:
        mirror_name, data = fetch_first_working()

    print(f"[+] Got offsets from: {mirror_name}")
    print(f"    Version: {data.get('Roblox Version', '?')}")
    print(f"    Dumper:  {data.get('Dumper Version', '?')}")
    print(f"    Dumped:  {data.get('Dumped At', '?')}")
    print(f"    Total:   {len(data.get('Offsets', {}))} structs")

    if args.json:
        out = json.dumps(data, indent=2)
    else:
        out = parse_to_cpp(data)

    if args.output:
        with open(args.output, "w") as f:
            f.write(out)
        print(f"[+] Wrote {len(out)} bytes to {args.output}")
    else:
        print(out)

if __name__ == "__main__":
    main()
