// ============================================================================
// AUTO-GENERATED by update_offsets.py — DO NOT EDIT BY HAND
// Source: theo mirror dump (version=version-e7d81637d42c4b23, dumped=17:43 02/09/2026, dumper=2.1.7)
// Generated: 2026-09-03T01:37:02.845028Z
// ============================================================================
#pragma once
#include <cstdint>

inline constexpr const char* kRobloxVersion = "version-e7d81637d42c4b23";

struct AirProperties {
    inline static constexpr uintptr_t AirDensity = 24;
    inline static constexpr uintptr_t GlobalWind = 60;
};

struct AnimationTrack {
    inline static constexpr uintptr_t Animation = 184;
    inline static constexpr uintptr_t Animator = 272;
    inline static constexpr uintptr_t IsPlaying = 2648;
    inline static constexpr uintptr_t Looped = 229;
    inline static constexpr uintptr_t Speed = 212;
    inline static constexpr uintptr_t TimePosition = 216;
};

struct Animator {
    inline static constexpr uintptr_t ActiveAnimations = 2896;
};

struct Atmosphere {
    inline static constexpr uintptr_t Color = 184;
    inline static constexpr uintptr_t Decay = 196;
    inline static constexpr uintptr_t Density = 208;
    inline static constexpr uintptr_t Glare = 212;
    inline static constexpr uintptr_t Haze = 216;
    inline static constexpr uintptr_t Offset = 220;
};

struct Attachment {
    inline static constexpr uintptr_t Position = 196;
};

struct BasePart {
    inline static constexpr uintptr_t CastShadow = 309;
    inline static constexpr uintptr_t Color3 = 424;
    inline static constexpr uintptr_t Locked = 310;
    inline static constexpr uintptr_t Massless = 311;
    inline static constexpr uintptr_t Primitive = 392;
    inline static constexpr uintptr_t Reflectance = 268;
    inline static constexpr uintptr_t Shape = 440;
    inline static constexpr uintptr_t Transparency = 304;
};

struct Beam {
    inline static constexpr uintptr_t Attachment0 = 352;
    inline static constexpr uintptr_t Attachment1 = 368;
    inline static constexpr uintptr_t Brightness = 384;
    inline static constexpr uintptr_t CurveSize0 = 388;
    inline static constexpr uintptr_t CurveSize1 = 392;
    inline static constexpr uintptr_t LightEmission = 396;
    inline static constexpr uintptr_t LightInfluence = 400;
    inline static constexpr uintptr_t Texture = 320;
    inline static constexpr uintptr_t TextureLength = 412;
    inline static constexpr uintptr_t TextureSpeed = 420;
    inline static constexpr uintptr_t Width0 = 424;
    inline static constexpr uintptr_t Width1 = 428;
    inline static constexpr uintptr_t ZOffset = 432;
};

struct BloomEffect {
    inline static constexpr uintptr_t Enabled = 176;
    inline static constexpr uintptr_t Intensity = 184;
    inline static constexpr uintptr_t Size = 188;
    inline static constexpr uintptr_t Threshold = 192;
};

struct BlurEffect {
    inline static constexpr uintptr_t Enabled = 176;
    inline static constexpr uintptr_t Size = 184;
};

struct ByteCode {
    inline static constexpr uintptr_t Pointer = 16;
    inline static constexpr uintptr_t Size = 32;
};

struct Camera {
    inline static constexpr uintptr_t CameraSubject = 200;
    inline static constexpr uintptr_t CameraType = 312;
    inline static constexpr uintptr_t FieldOfView = 320;
    inline static constexpr uintptr_t ImagePlaneDepth = 724;
    inline static constexpr uintptr_t Position = 252;
    inline static constexpr uintptr_t Rotation = 216;
    inline static constexpr uintptr_t Viewport = 652;
    inline static constexpr uintptr_t ViewportSize = 716;
};

struct CharacterMesh {
    inline static constexpr uintptr_t BaseTextureId = 200;
    inline static constexpr uintptr_t BodyPart = 328;
    inline static constexpr uintptr_t MeshId = 248;
    inline static constexpr uintptr_t OverlayTextureId = 296;
};

struct ClickDetector {
    inline static constexpr uintptr_t MaxActivationDistance = 232;
    inline static constexpr uintptr_t MouseIcon = 200;
};

struct Clothing {
    inline static constexpr uintptr_t Color3 = 288;
    inline static constexpr uintptr_t Template = 256;
};

struct ColorCorrectionEffect {
    inline static constexpr uintptr_t Brightness = 196;
    inline static constexpr uintptr_t Contrast = 200;
    inline static constexpr uintptr_t Enabled = 176;
    inline static constexpr uintptr_t TintColor = 184;
};

struct ColorGradingEffect {
    inline static constexpr uintptr_t Enabled = 176;
    inline static constexpr uintptr_t TonemapperPreset = 184;
};

struct DataModel {
    inline static constexpr uintptr_t CreatorId = 384;
    inline static constexpr uintptr_t GameId = 392;
    inline static constexpr uintptr_t GameLoaded = 1496;
    inline static constexpr uintptr_t JobId = 280;
    inline static constexpr uintptr_t PlaceId = 400;
    inline static constexpr uintptr_t PlaceVersion = 428;
    inline static constexpr uintptr_t PrimitiveCount = 1056;
    inline static constexpr uintptr_t ScriptContext = 1088;
    inline static constexpr uintptr_t ServerIP = 1472;
    inline static constexpr uintptr_t ToRenderView1 = 456;
    inline static constexpr uintptr_t ToRenderView2 = 8;
    inline static constexpr uintptr_t ToRenderView3 = 40;
    inline static constexpr uintptr_t Workspace = 344;
};

struct DepthOfFieldEffect {
    inline static constexpr uintptr_t Enabled = 176;
    inline static constexpr uintptr_t FarIntensity = 184;
    inline static constexpr uintptr_t FocusDistance = 188;
    inline static constexpr uintptr_t InFocusRadius = 192;
    inline static constexpr uintptr_t NearIntensity = 196;
};

struct DragDetector {
    inline static constexpr uintptr_t ActivatedCursorIcon = 448;
    inline static constexpr uintptr_t CursorIcon = 200;
    inline static constexpr uintptr_t MaxActivationDistance = 232;
    inline static constexpr uintptr_t MaxDragAngle = 680;
    inline static constexpr uintptr_t MaxDragTranslation = 620;
    inline static constexpr uintptr_t MaxForce = 684;
    inline static constexpr uintptr_t MaxTorque = 688;
    inline static constexpr uintptr_t MinDragAngle = 692;
    inline static constexpr uintptr_t MinDragTranslation = 632;
    inline static constexpr uintptr_t ReferenceInstance = 496;
    inline static constexpr uintptr_t Responsiveness = 704;
};

struct FakeDataModel {
    inline static constexpr uintptr_t Pointer = 147990632;
    inline static constexpr uintptr_t RealDataModel = 504;
};

struct GuiBase2D {
    inline static constexpr uintptr_t AbsolutePosition = 268;
    inline static constexpr uintptr_t AbsoluteRotation = 232;
    inline static constexpr uintptr_t AbsoluteSize = 276;
};

struct GuiObject {
    inline static constexpr uintptr_t BackgroundColor3 = 1344;
    inline static constexpr uintptr_t BackgroundTransparency = 1356;
    inline static constexpr uintptr_t BorderColor3 = 1356;
    inline static constexpr uintptr_t Image = 2440;
    inline static constexpr uintptr_t LayoutOrder = 1404;
    inline static constexpr uintptr_t Position = 1296;
    inline static constexpr uintptr_t RichText = 2952;
    inline static constexpr uintptr_t Rotation = 232;
    inline static constexpr uintptr_t ScreenGui_Enabled = 1220;
    inline static constexpr uintptr_t Size = 1328;
    inline static constexpr uintptr_t Text = 3568;
    inline static constexpr uintptr_t TextColor3 = 3744;
    inline static constexpr uintptr_t Visible = 1453;
    inline static constexpr uintptr_t ZIndex = 1444;
};

struct Humanoid {
    inline static constexpr uintptr_t AutoJumpEnabled = 468;
    inline static constexpr uintptr_t AutoRotate = 469;
    inline static constexpr uintptr_t AutomaticScalingEnabled = 470;
    inline static constexpr uintptr_t BreakJointsOnDeath = 471;
    inline static constexpr uintptr_t CameraOffset = 296;
    inline static constexpr uintptr_t DisplayDistanceType = 384;
    inline static constexpr uintptr_t DisplayName = 184;
    inline static constexpr uintptr_t EvaluateStateMachine = 472;
    inline static constexpr uintptr_t FloorMaterial = 388;
    inline static constexpr uintptr_t Health = 400;
    inline static constexpr uintptr_t HealthDisplayDistance = 392;
    inline static constexpr uintptr_t HealthDisplayType = 396;
    inline static constexpr uintptr_t HipHeight = 404;
    inline static constexpr uintptr_t HumanoidRootPart = 1144;
    inline static constexpr uintptr_t HumanoidState = 2240;
    inline static constexpr uintptr_t HumanoidStateID = 32;
    inline static constexpr uintptr_t IsWalking = 2407;
    inline static constexpr uintptr_t Jump = 474;
    inline static constexpr uintptr_t JumpHeight = 416;
    inline static constexpr uintptr_t JumpPower = 420;
    inline static constexpr uintptr_t MaxHealth = 424;
    inline static constexpr uintptr_t MaxSlopeAngle = 428;
    inline static constexpr uintptr_t MoveDirection = 320;
    inline static constexpr uintptr_t MoveToPart = 280;
    inline static constexpr uintptr_t MoveToPoint = 356;
    inline static constexpr uintptr_t NameDisplayDistance = 432;
    inline static constexpr uintptr_t NameOcclusion = 436;
    inline static constexpr uintptr_t PlatformStand = 476;
    inline static constexpr uintptr_t PlatformStatePointer = 0;
    inline static constexpr uintptr_t RequiresNeck = 477;
    inline static constexpr uintptr_t RigType = 448;
    inline static constexpr uintptr_t SeatPart = 264;
    inline static constexpr uintptr_t Sit = 477;
    inline static constexpr uintptr_t TargetPoint = 332;
    inline static constexpr uintptr_t UseJumpPower = 480;
    inline static constexpr uintptr_t WalkTimer = 1032;
    inline static constexpr uintptr_t Walkspeed = 464;
    inline static constexpr uintptr_t WalkspeedCheck = 956;
};

struct Instance {
    inline static constexpr uintptr_t ChildrenEnd = 8;
    inline static constexpr uintptr_t ChildrenStart = 120;
    inline static constexpr uintptr_t ClassBase = 432;
    inline static constexpr uintptr_t ClassDescriptor = 24;
    inline static constexpr uintptr_t ClassName = 8;
    inline static constexpr uintptr_t Name = 8;
    inline static constexpr uintptr_t NameContainer = 112;
    inline static constexpr uintptr_t Parent = 104;
    inline static constexpr uintptr_t This = 8;
};

struct Lighting {
    inline static constexpr uintptr_t Ambient = 208;
    inline static constexpr uintptr_t Brightness = 280;
    inline static constexpr uintptr_t ClockTime = 200;
    inline static constexpr uintptr_t ColorShift_Bottom = 232;
    inline static constexpr uintptr_t ColorShift_Top = 220;
    inline static constexpr uintptr_t EnvironmentDiffuseScale = 284;
    inline static constexpr uintptr_t EnvironmentSpecularScale = 288;
    inline static constexpr uintptr_t ExposureCompensation = 292;
    inline static constexpr uintptr_t FogColor = 244;
    inline static constexpr uintptr_t FogEnd = 300;
    inline static constexpr uintptr_t FogStart = 304;
    inline static constexpr uintptr_t GeographicLatitude = 308;
    inline static constexpr uintptr_t GlobalShadows = 324;
    inline static constexpr uintptr_t GradientBottom = 400;
    inline static constexpr uintptr_t GradientTop = 336;
    inline static constexpr uintptr_t LightColor = 348;
    inline static constexpr uintptr_t LightDirection = 360;
    inline static constexpr uintptr_t MoonPosition = 388;
    inline static constexpr uintptr_t OutdoorAmbient = 256;
    inline static constexpr uintptr_t Sky = 456;
    inline static constexpr uintptr_t Source = 372;
    inline static constexpr uintptr_t SunPosition = 376;
};

struct LocalScript {
    inline static constexpr uintptr_t ByteCode = 0;
    inline static constexpr uintptr_t GUID = 208;
    inline static constexpr uintptr_t Hash = 416;
};

struct MaterialColors {
    inline static constexpr uintptr_t Asphalt = 48;
    inline static constexpr uintptr_t Basalt = 39;
    inline static constexpr uintptr_t Brick = 15;
    inline static constexpr uintptr_t Cobblestone = 51;
    inline static constexpr uintptr_t Concrete = 12;
    inline static constexpr uintptr_t CrackedLava = 45;
    inline static constexpr uintptr_t Glacier = 27;
    inline static constexpr uintptr_t Grass = 6;
    inline static constexpr uintptr_t Ground = 42;
    inline static constexpr uintptr_t Ice = 54;
    inline static constexpr uintptr_t LeafyGrass = 57;
    inline static constexpr uintptr_t Limestone = 63;
    inline static constexpr uintptr_t Mud = 36;
    inline static constexpr uintptr_t Pavement = 66;
    inline static constexpr uintptr_t Rock = 24;
    inline static constexpr uintptr_t Salt = 60;
    inline static constexpr uintptr_t Sand = 18;
    inline static constexpr uintptr_t Sandstone = 33;
    inline static constexpr uintptr_t Slate = 9;
    inline static constexpr uintptr_t Snow = 30;
    inline static constexpr uintptr_t WoodPlanks = 21;
};

struct MeshContentProvider {
    inline static constexpr uintptr_t AssetID = 16;
    inline static constexpr uintptr_t Cache = 240;
    inline static constexpr uintptr_t LRUCache = 32;
    inline static constexpr uintptr_t MeshData = 64;
    inline static constexpr uintptr_t ToMeshData = 64;
};

struct MeshData {
    inline static constexpr uintptr_t FaceEnd = 56;
    inline static constexpr uintptr_t FaceStart = 48;
    inline static constexpr uintptr_t VertexEnd = 8;
    inline static constexpr uintptr_t VertexStart = 0;
};

struct MeshPart {
    inline static constexpr uintptr_t MeshId = 784;
    inline static constexpr uintptr_t Texture = 832;
};

struct Misc {
    inline static constexpr uintptr_t Adornee = 240;
    inline static constexpr uintptr_t AnimationId = 192;
    inline static constexpr uintptr_t StringLength = 16;
    inline static constexpr uintptr_t Value = 184;
};

struct Model {
    inline static constexpr uintptr_t PrimaryPart = 600;
    inline static constexpr uintptr_t Scale = 324;
};

struct ModuleScript {
    inline static constexpr uintptr_t ByteCode = 0;
    inline static constexpr uintptr_t GUID = 208;
    inline static constexpr uintptr_t Hash = 328;
    inline static constexpr uintptr_t IsCoreScript = 0;
};

struct MouseService {
    inline static constexpr uintptr_t InputObject = 240;
    inline static constexpr uintptr_t InputObject2 = 256;
    inline static constexpr uintptr_t MousePosition = 212;
    inline static constexpr uintptr_t SensitivityPointer = 0;
};

struct ParticleEmitter {
    inline static constexpr uintptr_t Acceleration = 480;
    inline static constexpr uintptr_t Brightness = 540;
    inline static constexpr uintptr_t Drag = 544;
    inline static constexpr uintptr_t Lifetime = 500;
    inline static constexpr uintptr_t LightEmission = 568;
    inline static constexpr uintptr_t LightInfluence = 572;
    inline static constexpr uintptr_t Rate = 584;
    inline static constexpr uintptr_t RotSpeed = 508;
    inline static constexpr uintptr_t Rotation = 516;
    inline static constexpr uintptr_t Speed = 524;
    inline static constexpr uintptr_t SpreadAngle = 532;
    inline static constexpr uintptr_t Texture = 448;
    inline static constexpr uintptr_t TimeScale = 604;
    inline static constexpr uintptr_t VelocityInheritance = 608;
    inline static constexpr uintptr_t ZOffset = 612;
};

struct Player {
    inline static constexpr uintptr_t AccountAge = 860;
    inline static constexpr uintptr_t CameraMode = 880;
    inline static constexpr uintptr_t DisplayName = 312;
    inline static constexpr uintptr_t HealthDisplayDistance = 916;
    inline static constexpr uintptr_t LocalPlayer = 304;
    inline static constexpr uintptr_t LocaleId = 280;
    inline static constexpr uintptr_t MaxZoomDistance = 872;
    inline static constexpr uintptr_t MinZoomDistance = 876;
    inline static constexpr uintptr_t ModelInstance = 664;
    inline static constexpr uintptr_t Mouse = 4616;
    inline static constexpr uintptr_t NameDisplayDistance = 932;
    inline static constexpr uintptr_t Team = 728;
    inline static constexpr uintptr_t TeamColor = 944;
    inline static constexpr uintptr_t UserId = 208;
};

struct PlayerConfigurer {
    inline static constexpr uintptr_t Pointer = 0;
};

struct PlayerMouse {
    inline static constexpr uintptr_t Icon = 200;
    inline static constexpr uintptr_t Workspace = 336;
};

struct Primitive {
    inline static constexpr uintptr_t AssemblyAngularVelocity = 260;
    inline static constexpr uintptr_t AssemblyLinearVelocity = 248;
    inline static constexpr uintptr_t Flags = 438;
    inline static constexpr uintptr_t Material = 0;
    inline static constexpr uintptr_t Owner = 528;
    inline static constexpr uintptr_t Position = 236;
    inline static constexpr uintptr_t Rotation = 200;
    inline static constexpr uintptr_t Size = 444;
    inline static constexpr uintptr_t Validate = 6;
};

struct PrimitiveFlags {
    inline static constexpr uintptr_t Anchored = 2;
    inline static constexpr uintptr_t CanCollide = 8;
    inline static constexpr uintptr_t CanQuery = 32;
    inline static constexpr uintptr_t CanTouch = 16;
};

struct ProximityPrompt {
    inline static constexpr uintptr_t ActionText = 176;
    inline static constexpr uintptr_t Enabled = 310;
    inline static constexpr uintptr_t GamepadKeyCode = 284;
    inline static constexpr uintptr_t HoldDuration = 288;
    inline static constexpr uintptr_t KeyCode = 292;
    inline static constexpr uintptr_t MaxActivationDistance = 296;
    inline static constexpr uintptr_t ObjectText = 208;
    inline static constexpr uintptr_t RequiresLineOfSight = 311;
};

struct RenderJob {
    inline static constexpr uintptr_t FakeDataModel = 56;
    inline static constexpr uintptr_t RealDataModel = 496;
    inline static constexpr uintptr_t RenderView = 472;
};

struct RenderView {
    inline static constexpr uintptr_t DeviceD3D11 = 8;
    inline static constexpr uintptr_t LightingValid = 336;
    inline static constexpr uintptr_t SkyValid = 653;
    inline static constexpr uintptr_t VisualEngine = 16;
};

struct RunService {
    inline static constexpr uintptr_t HeartbeatFPS = 192;
    inline static constexpr uintptr_t HeartbeatTask = 224;
};

struct Script {
    inline static constexpr uintptr_t ByteCode = 0;
    inline static constexpr uintptr_t GUID = 208;
    inline static constexpr uintptr_t Hash = 416;
};

struct ScriptContext {
    inline static constexpr uintptr_t RequireBypass = 0;
};

struct Seat {
    inline static constexpr uintptr_t Occupant = 536;
};

struct Sky {
    inline static constexpr uintptr_t MoonAngularSize = 580;
    inline static constexpr uintptr_t MoonTextureId = 200;
    inline static constexpr uintptr_t SkyboxBk = 248;
    inline static constexpr uintptr_t SkyboxDn = 296;
    inline static constexpr uintptr_t SkyboxFt = 344;
    inline static constexpr uintptr_t SkyboxLf = 392;
    inline static constexpr uintptr_t SkyboxOrientation = 568;
    inline static constexpr uintptr_t SkyboxRt = 440;
    inline static constexpr uintptr_t SkyboxUp = 488;
    inline static constexpr uintptr_t StarCount = 584;
    inline static constexpr uintptr_t SunAngularSize = 572;
    inline static constexpr uintptr_t SunTextureId = 536;
};

struct Sound {
    inline static constexpr uintptr_t IsPlaying = 320;
    inline static constexpr uintptr_t Looped = 317;
    inline static constexpr uintptr_t PlaybackSpeed = 284;
    inline static constexpr uintptr_t RollOffMaxDistance = 288;
    inline static constexpr uintptr_t RollOffMinDistance = 292;
    inline static constexpr uintptr_t SoundGroup = 232;
    inline static constexpr uintptr_t SoundId = 200;
    inline static constexpr uintptr_t Volume = 304;
};

struct SpawnLocation {
    inline static constexpr uintptr_t AllowTeamChangeOnTouch = 61;
    inline static constexpr uintptr_t Enabled = 497;
    inline static constexpr uintptr_t ForcefieldDuration = 488;
    inline static constexpr uintptr_t Neutral = 498;
    inline static constexpr uintptr_t TeamColor = 492;
};

struct SpecialMesh {
    inline static constexpr uintptr_t MeshId = 248;
    inline static constexpr uintptr_t Scale = 196;
};

struct StatsItem {
    inline static constexpr uintptr_t Value = 200;
};

struct SunRaysEffect {
    inline static constexpr uintptr_t Enabled = 176;
    inline static constexpr uintptr_t Intensity = 184;
    inline static constexpr uintptr_t Spread = 188;
};

struct SurfaceAppearance {
    inline static constexpr uintptr_t AlphaMode = 496;
    inline static constexpr uintptr_t Color = 472;
    inline static constexpr uintptr_t ColorMap = 200;
    inline static constexpr uintptr_t EmissiveMaskContent = 248;
    inline static constexpr uintptr_t EmissiveStrength = 500;
    inline static constexpr uintptr_t EmissiveTint = 484;
    inline static constexpr uintptr_t MetalnessMap = 296;
    inline static constexpr uintptr_t NormalMap = 344;
    inline static constexpr uintptr_t RoughnessMap = 392;
};

struct TaskScheduler {
    inline static constexpr uintptr_t JobEnd = 208;
    inline static constexpr uintptr_t JobName = 24;
    inline static constexpr uintptr_t JobStart = 200;
    inline static constexpr uintptr_t MaxFPS = 176;
    inline static constexpr uintptr_t Pointer = 145479464;
};

struct Team {
    inline static constexpr uintptr_t BrickColor = 184;
};

struct Terrain {
    inline static constexpr uintptr_t GrassLength = 496;
    inline static constexpr uintptr_t MaterialColors = 1208;
    inline static constexpr uintptr_t WaterColor = 480;
    inline static constexpr uintptr_t WaterReflectance = 504;
    inline static constexpr uintptr_t WaterTransparency = 508;
    inline static constexpr uintptr_t WaterWaveSize = 512;
    inline static constexpr uintptr_t WaterWaveSpeed = 516;
};

struct Textures {
    inline static constexpr uintptr_t Decal_Texture = 432;
    inline static constexpr uintptr_t Texture_Texture = 432;
};

struct Tool {
    inline static constexpr uintptr_t CanBeDropped = 1208;
    inline static constexpr uintptr_t Enabled = 1209;
    inline static constexpr uintptr_t Grip = 1196;
    inline static constexpr uintptr_t ManualActivationOnly = 1210;
    inline static constexpr uintptr_t RequiresHandle = 469;
    inline static constexpr uintptr_t TextureId = 864;
    inline static constexpr uintptr_t Tooltip = 1128;
};

struct UnionOperation {
    inline static constexpr uintptr_t AssetId = 784;
};

struct UserInputService {
    inline static constexpr uintptr_t WindowInputState = 704;
};

struct VehicleSeat {
    inline static constexpr uintptr_t MaxSpeed = 552;
    inline static constexpr uintptr_t SteerFloat = 556;
    inline static constexpr uintptr_t ThrottleFloat = 392;
    inline static constexpr uintptr_t Torque = 564;
    inline static constexpr uintptr_t TurnSpeed = 568;
};

struct VisualEngine {
    inline static constexpr uintptr_t Dimensions = 2832;
    inline static constexpr uintptr_t FakeDataModel = 2800;
    inline static constexpr uintptr_t Pointer = 137696264;
    inline static constexpr uintptr_t RenderView = 3120;
    inline static constexpr uintptr_t ViewMatrix = 432;
};

struct Weld {
    inline static constexpr uintptr_t Part0 = 280;
    inline static constexpr uintptr_t Part1 = 296;
};

struct WeldConstraint {
    inline static constexpr uintptr_t Part0 = 184;
    inline static constexpr uintptr_t Part1 = 200;
};

struct WindowInputState {
    inline static constexpr uintptr_t CapsLock = 64;
    inline static constexpr uintptr_t CurrentTextBox = 72;
};

struct Workspace {
    inline static constexpr uintptr_t CurrentCamera = 1208;
    inline static constexpr uintptr_t DistributedGameTime = 1240;
    inline static constexpr uintptr_t ReadOnlyGravity = 2544;
    inline static constexpr uintptr_t World = 1040;
};

struct World {
    inline static constexpr uintptr_t AirProperties = 576;
    inline static constexpr uintptr_t FallenPartsDestroyHeight = 544;
    inline static constexpr uintptr_t Gravity = 556;
    inline static constexpr uintptr_t Primitives = 688;
    inline static constexpr uintptr_t worldStepsPerSec = 1832;
};

// ============================================================================
// End of auto-generated offsets
// ============================================================================